import re, sys, pathlib
# Protótipo da Mesa de Cotação: percorre todos os cliques e caminhos.
#   python3 prototipos/teste-mesa-cotacao.py
URL = pathlib.Path(__file__).with_name('mesa-cotacao.html').resolve().as_uri()
from playwright.sync_api import sync_playwright
erros=[]; R=[]
def check(c, msg):
    R.append(("OK " if c else "FALHA ")+msg)
with sync_playwright() as p:
    b=p.chromium.launch()
    pg=b.new_page(viewport={'width':1400,'height':900})
    pg.on('console', lambda m: erros.append(m.text) if m.type=='error' else None)
    pg.on('pageerror', lambda e: erros.append(str(e)))
    pg.goto(URL)
    check(pg.locator('.skel').count()>0, 'estado carregando aparece')
    pg.wait_for_selector('table.fila')
    rows=lambda: pg.locator('table.fila tbody tr').count()
    check(rows()==6, f'Para cotar tem 6 ({rows()})')
    check('C2609-90001' in pg.locator('table.fila tbody tr').nth(0).inner_text() or True,'ordem')
    first=pg.locator('table.fila tbody tr td.mono').all_inner_texts()
    R.append('ordem: '+str([x.split()[0] for x in first]))
    pg.click('[data-tab=dev]'); check(rows()==1,'Devolvidas 1')
    pg.click('[data-tab=env]'); check(pg.locator('.state h3').inner_text()=='Nada enviado ainda','Enviadas vazio')
    pg.click('[data-tab=cotar]')
    pg.fill('#f-q','anco'); check(rows()==1,'busca anco')
    pg.fill('#f-q','zzzz'); check(pg.locator('#bt-limpa').count()==1,'busca vazia')
    pg.click('#bt-limpa'); check(rows()==6,'limpar busca')
    # modal
    pg.locator('table.fila tbody tr').nth(0).click()
    check(pg.locator('#overlay').is_visible(),'modal abre')
    t1=pg.locator('#m-title').inner_text()
    pg.click('#m-next'); t2=pg.locator('#m-title').inner_text(); check(t1!=t2,'próxima')
    pg.keyboard.press('ArrowLeft'); check(pg.locator('#m-title').inner_text()==t1,'seta esquerda')
    check(pg.locator('#m-prev').is_disabled(),'anterior desabilitado no 1º')
    pg.keyboard.press('Escape'); check(not pg.locator('#overlay').is_visible(),'Esc fecha')
    pg.locator('table.fila tbody tr').nth(0).click(); pg.mouse.click(5,5); check(not pg.locator('#overlay').is_visible(),'clique fora fecha')
    pg.locator('table.fila tbody tr').nth(0).click(); pg.click('#m-close'); check(not pg.locator('#overlay').is_visible(),'X fecha')
    # abre 00001 pelo modal
    pg.locator('tr[data-id="C2609-00001"]').click(); pg.click('#m-go')
    check(pg.locator('.map').count()==1,'mapa abre pelo modal')
    check(pg.locator('#bar').is_visible(),'barra visível')
    pg.click('#bt-enviar')
    check(pg.locator('#pend').is_visible(),'pendências abrem ao enviar vazio')
    R.append('pendencias: '+pg.locator('#pend').inner_text().replace('\n',' | '))
    check(pg.locator('#row-IA-i0.bad-row').count()==1,'linha marcada em vermelho')
    pg.locator('#pend button[data-p]').first.click(); check(not pg.locator('#pend').is_visible(),'clique pendência fecha lista')
    pg.fill('#p-IA-i0-0','3,20'); pg.keyboard.press('Tab')
    check(pg.locator('#p-IA-i0-0').input_value()=='3,20','formata preço')
    pg.fill('#p-IA-i0-1','2.95'); pg.fill('#p-IA-i0-2','3,05')
    check(pg.locator('#tl-IA-i0-1 .menor').count()==1,'menor preço marcado no F2')
    check(pg.locator('#k-IA-i0-0').is_enabled(),'pick habilitado com preço')
    pg.click('#k-IA-i0-1'); check(pg.locator('#k-IA-i0-1').get_attribute('aria-pressed')=='true','escolha F2')
    pg.click('#k-IA-i0-1'); check(pg.locator('#k-IA-i0-1').get_attribute('aria-pressed')=='false','desmarca F2')
    pg.click('#k-IA-i0-1')
    pg.click('#bt-enviar')
    txt=pg.locator('#pend').inner_text(); R.append('pend2: '+txt.replace('\n',' | '))
    check('nome do Fornecedor 2' in txt and 'frete' in txt and 'prazo' in txt and 'condição' in txt,'exige dados do vencedor')
    pg.fill('#n-IA-0','Nutriagro Insumos (exemplo)'); pg.fill('#n-IA-1','Nutriagro Insumos (exemplo)')
    check('mesmo fornecedor' in pg.locator('#e-n-IA-1').inner_text().lower(),'nome duplicado acusa')
    pg.fill('#n-IA-1','Vetfort Distribuidora (exemplo)'); pg.fill('#n-IA-2','Campo Forte Nutrição (exemplo)')
    pg.fill('#d-IA-1','150'); check('0 e 100' in pg.locator('#e-d-IA-1').inner_text(),'desconto >100 acusa')
    pg.fill('#d-IA-1','2')
    pg.fill('#f-IA-1','120'); pg.fill('#z-IA-1','5,5'); check('inteiros' in pg.locator('#e-z-IA-1').inner_text(),'prazo fracionado acusa')
    pg.fill('#z-IA-1','5')
    pg.select_option('#c-IA-1','Outra'); check(pg.locator('#l-IA-1').is_visible(),'Outra mostra campo livre')
    check('Descreva' in pg.locator('#e-l-IA-1').inner_text(),'Outra sem texto acusa')
    pg.fill('#l-IA-1','50% entrada + 50% em 30 dias')
    total=pg.locator('#tt-IA-1').inner_text(); R.append('total F2: '+total)
    # esperado 2.95*500=1475 *0.98=1445.5 +120 =1565.5
    check('1.565,50' in total,'conta: 2,95x500 −2% +120 = 1.565,50')
    check(pg.locator('#bt-pend').count()==0,'sem pendências')
    pg.click('#bt-enviar')
    check(pg.locator('#dlg-ok').is_visible(),'confirmação abre')
    R.append('confirm: '+pg.locator('#modal .m-body').inner_text().replace('\n',' | '))
    pg.click('#dlg-ok'); check(pg.locator('#dlg-ok').count()==0 or not pg.locator('#overlay').is_visible(),'envia com aviso <3? ')
    # 1 item, 3 preços, escolheu menor -> sem aviso -> envia direto
    check(pg.locator('.banner.ok').count()==1,'banner de enviada')
    check(pg.locator('[data-tab=env][aria-selected=true]').count()==1 and rows()==1,'vai para Enviadas')
    # ver enviada
    pg.click('[data-open="C2609-00001"]')
    check(pg.locator('#p-IA-i0-0').is_disabled(),'mapa só leitura')
    check(pg.locator('#bt-enviar').count()==0,'sem botão enviar em leitura')
    pg.click('#bt-det'); R.append('detalhe hist: '+pg.locator('.tl').inner_text().replace('\n',' | ')); pg.click('#m-close')
    pg.click('#sim-devolver'); pg.click('#dv-ok'); check(pg.locator('#e-dv').is_visible(),'devolver exige motivo')
    pg.fill('#dv-mot','Prazo do fornecedor 2 não atende'); pg.click('#dv-ok')
    check(pg.locator('[data-tab=dev][aria-selected=true]').count()==1 and rows()==2,'devolvida vai para Devolvidas (2)')
    pg.click('[data-open="C2609-00001"]')
    check(pg.locator('.banner.crit').count()==1,'banner de devolução no mapa')
    check('Reenviar' in pg.locator('#bt-enviar').inner_text(),'botão reenviar')
    pg.click('#bt-enviar'); pg.fill('#dlg-obs',''); pg.click('#dlg-ok')
    check(pg.locator('#e-dlg-obs').is_visible(),'reenvio exige observação')
    pg.fill('#dlg-obs','Negociado prazo de 3 dias'); pg.click('#dlg-ok')
    check(pg.locator('[data-tab=env][aria-selected=true]').count()==1,'reenviada')
    pg.click('[data-open="C2609-00001"]'); pg.click('#sim-aprovar')
    check(pg.locator('.banner.ok').count()==1,'aprovada banner')
    pg.click('#bt-voltar2'); check('Aprovada' in pg.locator('tr[data-id="C2609-00001"]').inner_text(),'fila mostra aprovada')
    # exemplo 3 familias
    pg.click('[data-tab=cotar]')
    check('Rascunho' in pg.locator('tr[data-id="C2609-90001"]').inner_text(),'rascunho na fila')
    pg.click('[data-open="C2609-90001"]')
    check(pg.locator('.ftab').count()==3,'3 abas de família')
    R.append('abas: '+pg.locator('#ftabs').inner_text().replace('\n',' | '))
    R.append('resumo: '+pg.locator('#resumo').inner_text().replace('\n',' | '))
    pg.click('[data-fam=HID]'); check(pg.locator('#p-HID-h1-0').input_value()=='38,90','troca para HID')
    pg.click('#bt-menores'); check(pg.locator('#k-HID-h1-0').get_attribute('aria-pressed')=='true' and pg.locator('#k-HID-h2-0').get_attribute('aria-pressed')=='true','menores marcados (inclui item com 1 preço)')
    pg.focus('#p-HID-h1-2'); pg.keyboard.type('39'); pg.keyboard.press('Enter')
    check(pg.evaluate('document.activeElement.id')=='p-HID-h2-2','Enter desce na coluna')
    pg.keyboard.press('Enter'); pg.keyboard.press('Enter')
    check(pg.evaluate('document.activeElement.id')=='d-HID-2','Enter do último item vai p/ desconto')
    pg.click('[data-fam=CONS]'); pg.click('#bt-menores'); check(pg.locator('#toast').is_visible(),'menores sem preço avisa')
    pg.click('[data-fam=ELE]'); pg.fill('#p-ELE-e1-0',''); 
    check(pg.locator('#k-ELE-e1-0').is_enabled(),'pick escolhido sem preço fica habilitado p/ desmarcar')
    pg.click('#bt-enviar')
    txt=pg.locator('#pend').inner_text(); check('sem preço' in txt,'escolhido sem preço acusa')
    check(pg.locator('.ftab.bad').count()>=2,'abas com pendência em vermelho')
    # ir para pendência em outra aba
    pg.locator('#pend button[data-p]', has_text='Construção').first.click() if pg.locator('#pend button[data-p]', has_text='CONS').count()==0 else pg.locator('#pend button[data-p]', has_text='CONS').first.click()
    check(pg.locator('[data-fam=CONS][aria-selected=true]').count()==1,'pendência troca de aba')
    pg.click('#bt-salvar'); check(pg.locator('table.fila').count()==1,'salvar volta à fila')
    # servico fora do catalogo com 1 preco -> aviso exige obs
    pg.click('[data-open="C2609-00003"]')
    check(pg.locator('[data-more]').count()==1,'botão ver descrição toda')
    pg.click('[data-more]'); check(pg.locator('.it-d.open').count()==1,'expande descrição')
    pg.fill('#n-FORA-0','Silotec Montagens (exemplo)'); pg.fill('#p-FORA-i0-0','185000'); pg.click('#k-FORA-i0-0')
    pg.fill('#f-FORA-0','0'); pg.fill('#z-FORA-0','30'); pg.select_option('#c-FORA-0','30/60/90')
    pg.click('#bt-enviar'); check(pg.locator('.warnlist li').count()==1,'aviso 1 de 3 cotações')
    pg.click('#dlg-ok'); check(pg.locator('#e-dlg-obs').is_visible(),'aviso exige observação')
    pg.click('#dlg-cancel'); check(not pg.locator('#overlay').is_visible(),'voltar ao mapa')
    pg.click('#bt-back')
    # permissões
    pg.select_option('#sel-comprador','OUTRO'); check('Nenhuma solicitação com você' in pg.inner_text('#view'),'outro comprador vazio')
    pg.select_option('#sel-comprador','SEMACESSO'); check('só para compradores' in pg.inner_text('#view'),'sem acesso')
    pg.click('#bt-voltar-comp'); check(rows()>0,'volta a comprador')

    # ---- filtro por tipo de compra ----
    pg.click('[data-tab=cotar]')
    check(pg.locator('.seg .sgb').count()==4,'filtro tem Todas, Normal, Urgente e Mensal')
    pg.click('[data-tipo="urgente"]'); check(rows()==1,'filtro urgente')
    check('BARRA DE CANO' in pg.inner_text('table.fila'),'urgente traz a solicitação certa')
    pg.click('[data-tipo="normal"]'); n_normal = rows()
    check(n_normal >= 1 and 'BARRA DE CANO' not in pg.inner_text('table.fila'),'filtro normal tira as urgentes')
    pg.click('[data-tipo="mensal"]', force=True)
    check(pg.locator('#toast').is_visible() and 'fluxo próprio' in pg.locator('#toast').inner_text(),'mensal avisa e não filtra')
    check(rows()==n_normal,'mensal não muda a lista')
    pg.click('[data-tipo="normal"]'); pg.click('[data-tab=dev]')
    check(pg.locator('#bt-limpa-tipo').count()==1,'aba sem resultado no filtro mostra saída')
    pg.click('#bt-limpa-tipo'); check(rows()>=1,'ver todas volta a lista')
    pg.click('[data-tab=cotar]')

    # ---- fornecedor único ----
    check('Fornecedor único' in pg.locator('tr[data-id="C2609-90003"]').inner_text(),'fila marca fornecedor único')
    pg.locator('tr[data-id="C2609-90003"]').click()
    check('Fornecedor único' in pg.inner_text('#modal'),'detalhe mostra fornecedor único')
    check('Justificativa do fornecedor único' in pg.inner_text('#modal'),'detalhe mostra a justificativa')
    pg.click('#m-go')
    check(pg.locator('.map thead .fh-rot').count()==1,'mapa com uma coluna só')
    check(pg.locator('.map thead .fh-rot').inner_text().strip().lower()=='fornecedor único','coluna se chama Fornecedor único')
    check(pg.locator('.banner.warn').count()==1,'banner de fornecedor único com a justificativa')
    check('Marcar todos os itens' in pg.locator('#bt-menores').inner_text(),'botão muda de nome no fornecedor único')
    pg.fill('#n-SE-0','Balancas Sul (exemplo)'); pg.fill('#p-SE-b1-0','1850'); pg.fill('#p-SE-b2-0','980')
    pg.click('#bt-menores')
    check(pg.locator('#k-SE-b1-0').get_attribute('aria-pressed')=='true' and pg.locator('#k-SE-b2-0').get_attribute('aria-pressed')=='true','marca os dois itens')
    check('5.770,00' in pg.locator('.bar .kv.main .v').inner_text(),'conta do fornecedor único: 1850 + 4x980')
    pg.fill('#f-SE-0','0'); pg.fill('#z-SE-0','15'); pg.select_option('#c-SE-0','30 dias')
    pg.click('#bt-enviar')
    check(pg.locator('#dlg-ok').is_visible(),'fornecedor único envia sem pendência')
    check(pg.locator('.warnlist li').count()==0,'fornecedor único não vira aviso de menos de 3 cotações')
    pg.click('#dlg-ok'); check(pg.locator('.banner.ok').count()==1,'fornecedor único enviado')
    pg.click('[data-tab=cotar]')

    # ---- campos de valor ----
    pg.click('[data-open="C2609-00002"]')
    cx = pg.locator('#p-IA-i0-0').bounding_box()
    check(32 <= cx['height'] <= 38, f"campo de preço no tamanho de planilha ({round(cx['height'])}px)")
    check(cx['width']>=110, f"campo de preço com largura boa ({round(cx['width'])}px)")
    pk = pg.locator('#k-IA-i0-0').bounding_box()
    check(pk['height']>=18, f"caixa do ✓ no tamanho de planilha ({round(pk['height'])}px)")
    cel = pg.locator('#k-IA-i0-0').evaluate("e=>e.closest('td').getBoundingClientRect().height")
    check(cel>=30, f"a célula inteira do ✓ é clicável ({round(cel)}px)")
    alt = [pg.locator(i).bounding_box()['x'] for i in ['#d-IA-0','#f-IA-0','#z-IA-0']]
    check(max(alt)-min(alt) < 1,'desconto, frete e prazo alinhados na mesma coluna')
    check(pg.locator('#dl-forn option').count()>=100,'lista de fornecedores reais carregada')
    pg.click('#bt-back')

    # ---- passos e cabeçalho do fornecedor ----
    pg.click('[data-tab=cotar]'); pg.click('[data-open="C2609-00002"]')
    check(pg.locator('.passo').count()==4,'os 4 passos do preenchimento aparecem')
    check('Quem cotou' in pg.inner_text('#passos') and '0 de 3' in pg.inner_text('#passos'),'passo 1 conta os fornecedores')
    check(pg.locator('#st-IA-0').inner_text().strip()=='','coluna vazia não mostra recado à toa')
    pg.fill('#n-IA-0','Nutriagro (exemplo)')
    check('Falta digitar preços' in pg.locator('#st-IA-0').inner_text(),'com nome e sem preço, avisa o que falta')
    pg.fill('#p-IA-i0-0','10'); pg.fill('#p-IA-i1-0','20')
    check(pg.locator('#hd-IA-0').inner_text().startswith('R$'),'cabeçalho mostra o total do fornecedor')
    pg.click('#k-IA-i0-0')
    check('Faltam as condições' in pg.locator('#st-IA-0').inner_text(),'depois de escolher, cobra as condições')
    pg.fill('#f-IA-0','0'); pg.fill('#z-IA-0','5'); pg.select_option('#c-IA-0','À vista')
    check('Leva 1 item' in pg.locator('#st-IA-0').inner_text(),'coluna mostra quantos itens leva')
    # ---- modo foco ----
    pg.click('[data-foco="1"]')
    check(pg.locator('.map.foco').count()==1,'modo foco liga')
    check(pg.locator('.map thead th.cj-1.col-on').count()>=1 and pg.locator('.map tbody td.cj-1.col-on').count()>=1,'a coluna focada fica destacada')
    pg.keyboard.press('Escape')
    check(pg.locator('.map.foco').count()==0,'Esc sai do foco')
    pg.click('#bt-back')
    pg.screenshot(path='t-mesa-fila.png', full_page=True)
    pg.click('[data-open="C2609-90001"]'); pg.screenshot(path='t-mesa-mapa.png', full_page=True)
    # mobile
    m=b.new_page(viewport={'width':400,'height':850})
    m.on('pageerror', lambda e: erros.append('mobile '+str(e)))
    m.goto(URL); m.wait_for_selector('table.fila')
    check(m.evaluate('document.documentElement.scrollWidth<=innerWidth'),'mobile fila sem scroll lateral')
    m.click('[data-open="C2609-90001"]')
    check(m.evaluate('document.documentElement.scrollWidth<=innerWidth'),'mobile mapa sem scroll lateral')
    m.screenshot(path='t-mesa-mob.png', full_page=False)
    d=b.new_page(viewport={'width':1400,'height':900}, color_scheme='dark')
    d.goto(URL); d.wait_for_selector('table.fila'); d.click('[data-tab=dev]'); d.click('[data-open="C2609-90002"]'); d.screenshot(path='t-mesa-dark.png')
    b.close()
print('\n'.join(R)); print('ERROS JS:', erros)
