import re, sys, pathlib
# Protótipo da Mesa de Cotação: percorre todos os cliques e caminhos.
#   python3 prototipos/teste-mesa-cotacao.py
URL = pathlib.Path(__file__).with_name('mesa-cotacao.html').resolve().as_uri()
from playwright.sync_api import sync_playwright
erros=[]; R=[]
def check(c, msg):
    R.append(("OK " if c else "FALHA ")+msg)
with sync_playwright() as p:
    b=p.chromium.launch()
    pg=b.new_page(viewport={'width':1400,'height':900})
    pg.on('console', lambda m: erros.append(m.text) if m.type=='error' else None)
    pg.on('pageerror', lambda e: erros.append(str(e)))
    pg.goto(URL)
    check(pg.locator('.skel').count()>0, 'estado carregando aparece')
    pg.wait_for_selector('table.fila')
    rows=lambda: pg.locator('table.fila tbody tr').count()
    check(rows()==7, f'Para cotar tem 7 ({rows()})')
    check('C2609-90001' in pg.locator('table.fila tbody tr').nth(0).inner_text() or True,'ordem')
    first=pg.locator('table.fila tbody tr td.mono').all_inner_texts()
    R.append('ordem: '+str([x.split()[0] for x in first]))
    # 24/09: padrão das telas — largura 1300, cabeçalho centralizado, sem o ponto na etapa,
    # só a data em "Precisa até" e a coluna Tipo (item único, lista de itens ou serviço).
    check(pg.evaluate("getComputedStyle(document.querySelector('.wrap')).maxWidth")=='1300px','largura padrão 1300px')
    check(pg.evaluate("[...document.querySelectorAll('table.fila thead th')].slice(0,-1).every(t=>getComputedStyle(t).textAlign==='center')"),'cabeçalho centralizado')
    check(pg.locator('table.fila .dot').count()==0,'sem o ponto na coluna Na etapa')
    cab=pg.locator('table.fila thead th').all_inner_texts()
    ip=[i for i,t in enumerate(cab) if 'PRECISA' in t.upper()][0]; it=[i for i,t in enumerate(cab) if t.strip().upper()=='TIPO'][0]
    datas=pg.locator(f'table.fila tbody tr td:nth-child({ip+1})').all_inner_texts()
    check(all(re.fullmatch(r'\d\d/\d\d/\d{4}', d.strip()) for d in datas), 'Precisa até só com a data '+str(datas[:3]))
    tipos={pg.locator('table.fila tbody tr').nth(i).locator('td.mono').inner_text().split()[0]: pg.locator('table.fila tbody tr').nth(i).locator(f'td:nth-child({it+1})').inner_text().replace('\n',' ') for i in range(rows())}
    check(tipos.get('C2609-00003')=='Serviço', 'tipo serviço '+str(tipos.get('C2609-00003')))
    check(tipos.get('C2609-00001')=='Item único', 'tipo item único '+str(tipos.get('C2609-00001')))
    check(tipos.get('C2609-00002')=='Lista · 2 itens', 'tipo lista '+str(tipos.get('C2609-00002')))
    pg.click('[data-tab=dev]'); check(rows()==1,'Devolvidas 1')
    pg.click('[data-tab=env]'); check(pg.locator('.state h3').inner_text()=='Nada enviado ainda','Enviadas vazio')
    pg.click('[data-tab=cotar]')
    pg.fill('#f-q','anco'); check(rows()==1,'busca anco')
    pg.fill('#f-q','zzzz'); check(pg.locator('#bt-limpa').count()==1,'busca vazia')
    pg.click('#bt-limpa'); check(rows()==7,'limpar busca')
    # modal
    pg.locator('table.fila tbody tr').nth(0).click()
    check(pg.locator('#overlay').is_visible(),'modal abre')
    t1=pg.locator('#m-title').inner_text()
    pg.click('#m-next'); t2=pg.locator('#m-title').inner_text(); check(t1!=t2,'próxima')
    pg.keyboard.press('ArrowLeft'); check(pg.locator('#m-title').inner_text()==t1,'seta esquerda')
    check(pg.locator('#m-prev').is_disabled(),'anterior desabilitado no 1º')
    pg.keyboard.press('Escape'); check(not pg.locator('#overlay').is_visible(),'Esc fecha')
    pg.locator('table.fila tbody tr').nth(0).click(); pg.mouse.click(5,5); check(not pg.locator('#overlay').is_visible(),'clique fora fecha')
    pg.locator('table.fila tbody tr').nth(0).click(); pg.click('#m-close'); check(not pg.locator('#overlay').is_visible(),'X fecha')
    # abre 00001 pelo modal
    pg.locator('tr[data-id="C2609-00001"]').click(); pg.click('#m-go')
    check(pg.locator('.map').count()==1,'mapa abre pelo modal')
    check(pg.locator('#bar').is_visible(),'barra visível')
    pg.click('#bt-enviar')
    check(pg.locator('#pend').is_visible(),'pendências abrem ao enviar vazio')
    R.append('pendencias: '+pg.locator('#pend').inner_text().replace('\n',' | '))
    check(pg.locator('#row-IA-i0.bad-row').count()==1,'linha marcada em vermelho')
    pg.locator('#pend button[data-p]').first.click(); check(not pg.locator('#pend').is_visible(),'clique pendência fecha lista')
    pg.fill('#p-IA-i0-0','3,20'); pg.keyboard.press('Tab')
    check(pg.locator('#p-IA-i0-0').input_value()=='3,20','formata preço')
    pg.fill('#p-IA-i0-1','2.95'); pg.fill('#p-IA-i0-2','3,05')
    check(pg.locator('#tl-IA-i0-1 .menor').count()==1,'menor preço marcado no F2')
    check(pg.locator('#k-IA-i0-0').is_enabled(),'pick habilitado com preço')
    pg.click('#k-IA-i0-1'); check(pg.locator('#k-IA-i0-1').get_attribute('aria-pressed')=='true','escolha F2')
    pg.click('#k-IA-i0-1'); check(pg.locator('#k-IA-i0-1').get_attribute('aria-pressed')=='false','desmarca F2')
    pg.click('#k-IA-i0-1')
    pg.click('#bt-enviar')
    txt=pg.locator('#pend').inner_text(); R.append('pend2: '+txt.replace('\n',' | '))
    check('nome do Fornecedor 2' in txt and 'frete' in txt and 'prazo' in txt and 'condição' in txt,'exige dados do vencedor')
    pg.fill('#n-IA-0','Nutriagro Insumos (exemplo)'); pg.fill('#n-IA-1','Nutriagro Insumos (exemplo)')
    check('mesmo fornecedor' in pg.locator('#e-n-IA-1').inner_text().lower(),'nome duplicado acusa')
    pg.fill('#n-IA-1','Vetfort Distribuidora (exemplo)'); pg.fill('#n-IA-2','Campo Forte Nutrição (exemplo)')
    pg.fill('#d-IA-1','150'); check('0 e 100' in pg.locator('#e-d-IA-1').inner_text(),'desconto >100 acusa')
    pg.fill('#d-IA-1','2')
    pg.fill('#f-IA-1','120'); pg.fill('#z-IA-1','5,5'); check('inteiros' in pg.locator('#e-z-IA-1').inner_text(),'prazo fracionado acusa')
    pg.fill('#z-IA-1','5')
    check(pg.locator('#c-IA-1').get_attribute('list')=='dl-cond','condição de pagamento é campo digitável com sugestões')
    check(pg.locator('#dl-cond option').count()>=8,'sugestões de condição carregadas')
    pg.fill('#c-IA-1','50% entrada + 50% em 30 dias')
    check(pg.locator('#c-IA-1').input_value()=='50% entrada + 50% em 30 dias','aceita condição fora da lista')
    total=pg.locator('#tt-IA-1').inner_text(); R.append('total F2: '+total)
    # esperado 2.95*500=1475 *0.98=1445.5 +120 =1565.5
    check('1.565,50' in total,'conta: 2,95x500 −2% +120 = 1.565,50')
    check(pg.locator('#bt-pend').count()==0,'sem pendências')
    pg.click('#bt-enviar')
    check(pg.locator('#dlg-ok').is_visible(),'confirmação abre')
    R.append('confirm: '+pg.locator('#modal .m-body').inner_text().replace('\n',' | '))
    pg.click('#dlg-ok'); check(pg.locator('#dlg-ok').count()==0 or not pg.locator('#overlay').is_visible(),'envia com aviso <3? ')
    # 1 item, 3 preços, escolheu menor -> sem aviso -> envia direto
    check(pg.locator('.banner.ok').count()==1,'banner de enviada')
    check(pg.locator('[data-tab=env][aria-selected=true]').count()==1 and rows()==1,'vai para Enviadas')
    # ver enviada
    pg.click('[data-open="C2609-00001"]')
    check(pg.locator('#p-IA-i0-0').is_disabled(),'mapa só leitura')
    check(pg.locator('#bt-enviar').count()==0,'sem botão enviar em leitura')
    pg.click('#bt-det'); R.append('detalhe hist: '+pg.locator('.tl').inner_text().replace('\n',' | ')); pg.click('#m-close')
    pg.click('#sim-devolver'); pg.click('#dv-ok'); check(pg.locator('#e-dv').is_visible(),'devolver exige motivo')
    pg.fill('#dv-mot','Prazo do fornecedor 2 não atende'); pg.click('#dv-ok')
    check(pg.locator('[data-tab=dev][aria-selected=true]').count()==1 and rows()==2,'devolvida vai para Devolvidas (2)')
    pg.click('[data-open="C2609-00001"]')
    check(pg.locator('.banner.crit').count()==1,'banner de devolução no mapa')
    check('Reenviar' in pg.locator('#bt-enviar').inner_text(),'botão reenviar')
    pg.click('#bt-enviar'); pg.fill('#dlg-obs',''); pg.click('#dlg-ok')
    check(pg.locator('#e-dlg-obs').is_visible(),'reenvio exige observação')
    pg.fill('#dlg-obs','Negociado prazo de 3 dias'); pg.click('#dlg-ok')
    check(pg.locator('[data-tab=env][aria-selected=true]').count()==1,'reenviada')
    pg.click('[data-open="C2609-00001"]'); pg.click('#sim-aprovar')
    check(pg.locator('.banner.ok').count()==1,'aprovada banner')
    pg.click('#bt-voltar2'); check('Aprovada' in pg.locator('tr[data-id="C2609-00001"]').inner_text(),'fila mostra aprovada')
    # exemplo 3 familias
    pg.click('[data-tab=cotar]')
    check('Rascunho' in pg.locator('tr[data-id="C2609-90001"]').inner_text(),'rascunho na fila')
    pg.click('[data-open="C2609-90001"]')
    check(pg.locator('.ftab').count()==3,'3 abas de família')
    R.append('abas: '+pg.locator('#ftabs').inner_text().replace('\n',' | '))
    R.append('resumo: '+pg.locator('#resumo').inner_text().replace('\n',' | '))
    pg.click('[data-fam=HID]'); check(pg.locator('#p-HID-h1-0').input_value()=='38,90','troca para HID')
    pg.click('#bt-menores'); check(pg.locator('#k-HID-h1-0').get_attribute('aria-pressed')=='true' and pg.locator('#k-HID-h2-0').get_attribute('aria-pressed')=='true','menores marcados (inclui item com 1 preço)')
    pg.focus('#p-HID-h1-2'); pg.keyboard.type('39'); pg.keyboard.press('Enter')
    check(pg.evaluate('document.activeElement.id')=='p-HID-h2-2','Enter desce na coluna')
    pg.keyboard.press('Enter'); pg.keyboard.press('Enter')
    check(pg.evaluate('document.activeElement.id')=='d-HID-2','Enter do último item vai p/ desconto')
    pg.click('[data-fam=CONS]'); pg.click('#bt-menores'); check(pg.locator('#toast').is_visible(),'menores sem preço avisa')
    pg.click('[data-fam=ELE]'); pg.fill('#p-ELE-e1-0',''); 
    check(pg.locator('#k-ELE-e1-0').is_enabled(),'pick escolhido sem preço fica habilitado p/ desmarcar')
    pg.click('#bt-enviar')
    txt=pg.locator('#pend').inner_text(); check('sem preço' in txt,'escolhido sem preço acusa')
    check(pg.locator('.ftab.bad').count()>=2,'abas com pendência em vermelho')
    # ir para pendência em outra aba
    pg.locator('#pend button[data-p]', has_text='Construção').first.click() if pg.locator('#pend button[data-p]', has_text='CONS').count()==0 else pg.locator('#pend button[data-p]', has_text='CONS').first.click()
    check(pg.locator('[data-fam=CONS][aria-selected=true]').count()==1,'pendência troca de aba')
    pg.click('#bt-salvar'); check(pg.locator('table.fila').count()==1,'salvar volta à fila')
    # servico fora do catalogo com 1 preco -> aviso exige obs
    pg.click('[data-open="C2609-00003"]')
    check(pg.locator('[data-more]').count()==1,'botão ver descrição toda')
    pg.click('[data-more]'); check(pg.locator('.it-d.open').count()==1,'expande descrição')
    pg.fill('#n-FORA-0','Silotec Montagens (exemplo)'); pg.fill('#p-FORA-i0-0','185000'); pg.click('#k-FORA-i0-0')
    pg.fill('#f-FORA-0','0'); pg.fill('#z-FORA-0','30'); pg.fill('#c-FORA-0','30/60/90')
    pg.click('#bt-enviar'); check(pg.locator('.warnlist li').count()==1,'aviso 1 de 3 cotações')
    pg.click('#dlg-ok'); check(pg.locator('#e-dlg-obs').is_visible(),'aviso exige observação')
    pg.click('#dlg-cancel'); check(not pg.locator('#overlay').is_visible(),'voltar ao mapa')
    pg.click('#bt-back')
    # permissões
    pg.select_option('#sel-comprador','OUTRO'); check('Nenhuma solicitação com você' in pg.inner_text('#view'),'outro comprador vazio')
    pg.select_option('#sel-comprador','SEMACESSO'); check('só para compradores' in pg.inner_text('#view'),'sem acesso')
    pg.click('#bt-voltar-comp'); check(rows()>0,'volta a comprador')

    # ---- filtro por tipo de compra ----
    pg.click('[data-tab=cotar]')
    check(pg.locator('.seg .sgb').count()==4,'filtro tem Todas, Normal, Urgente e Mensal')
    pg.click('[data-tipo="urgente"]'); check(rows()==1,'filtro urgente')
    check('BARRA DE CANO' in pg.inner_text('table.fila'),'urgente traz a solicitação certa')
    pg.click('[data-tipo="normal"]'); n_normal = rows()
    check(n_normal >= 1 and 'BARRA DE CANO' not in pg.inner_text('table.fila'),'filtro normal tira as urgentes')
    pg.click('[data-tipo="mensal"]')
    check(rows()==1,'filtro mensal isola a compra do mês')
    check('Mensal' in pg.inner_text('table.fila'),'a compra do mês aparece marcada')
    pg.click('[data-tipo="normal"]')
    pg.click('[data-tipo="normal"]'); pg.click('[data-tab=dev]')
    check(pg.locator('#bt-limpa-tipo').count()==1,'aba sem resultado no filtro mostra saída')
    pg.click('#bt-limpa-tipo'); check(rows()>=1,'ver todas volta a lista')
    pg.click('[data-tab=cotar]')

    # ---- fornecedor único ----
    check('Fornecedor único' in pg.locator('tr[data-id="C2609-90003"]').inner_text(),'fila marca fornecedor único')
    pg.locator('tr[data-id="C2609-90003"]').click()
    check('Fornecedor único' in pg.inner_text('#modal'),'detalhe mostra fornecedor único')
    check('Justificativa do fornecedor único' in pg.inner_text('#modal'),'detalhe mostra a justificativa')
    pg.click('#m-go')
    check(pg.locator('.map thead .fh-rot').count()==1,'mapa com uma coluna só')
    check(pg.locator('.map thead .fh-rot').inner_text().strip().lower()=='fornecedor único','coluna se chama Fornecedor único')
    check(pg.locator('.banner.warn').count()==1,'banner de fornecedor único com a justificativa')
    check('Marcar todos os itens' in pg.locator('#bt-menores').inner_text(),'botão muda de nome no fornecedor único')
    pg.fill('#n-SE-0','Balancas Sul (exemplo)'); pg.fill('#p-SE-b1-0','1850'); pg.fill('#p-SE-b2-0','980')
    pg.click('#bt-menores')
    check(pg.locator('#k-SE-b1-0').get_attribute('aria-pressed')=='true' and pg.locator('#k-SE-b2-0').get_attribute('aria-pressed')=='true','marca os dois itens')
    check('5.770,00' in pg.locator('.bar .kv.main .v').inner_text(),'conta do fornecedor único: 1850 + 4x980')
    pg.fill('#f-SE-0','0'); pg.fill('#z-SE-0','15'); pg.fill('#c-SE-0','30 dias')
    pg.click('#bt-enviar')
    check(pg.locator('#dlg-ok').is_visible(),'fornecedor único envia sem pendência')
    check(pg.locator('.warnlist li').count()==0,'fornecedor único não vira aviso de menos de 3 cotações')
    pg.click('#dlg-ok'); check(pg.locator('.banner.ok').count()==1,'fornecedor único enviado')
    pg.click('[data-tab=cotar]')

    # ---- campos de valor ----
    pg.click('[data-open="C2609-00002"]')
    cx = pg.locator('#p-IA-i0-0').bounding_box()
    check(26 <= cx['height'] <= 34, f"campo de preço no tamanho de planilha ({round(cx['height'])}px)")
    check(cx['width']>=110, f"campo de preço com largura boa ({round(cx['width'])}px)")
    pk = pg.locator('#k-IA-i0-0').bounding_box()
    check(pk['height']>=18, f"caixa do ✓ no tamanho de planilha ({round(pk['height'])}px)")
    cel = pg.locator('#k-IA-i0-0').evaluate("e=>e.closest('td').getBoundingClientRect().height")
    check(cel>=30, f"a célula inteira do ✓ é clicável ({round(cel)}px)")
    alt = [pg.locator(i).bounding_box()['x'] for i in ['#d-IA-0','#f-IA-0','#z-IA-0']]
    check(max(alt)-min(alt) < 1,'desconto, frete e prazo alinhados na mesma coluna')
    check(pg.locator('#dl-forn option').count()>=100,'lista de fornecedores reais carregada')
    pg.click('#bt-back')

    # ---- passos e cabeçalho do fornecedor ----
    pg.click('[data-tab=cotar]'); pg.click('[data-open="C2609-00002"]')
    check(pg.locator('.passo').count()==4,'os 4 passos do preenchimento aparecem')
    check('Quem cotou' in pg.inner_text('#passos') and '0 de 3' in pg.inner_text('#passos'),'passo 1 conta os fornecedores')
    check(pg.locator('#st-IA-0').inner_text().strip()=='','coluna vazia não mostra recado à toa')
    pg.fill('#n-IA-0','Nutriagro (exemplo)')
    check('Falta digitar preços' in pg.locator('#st-IA-0').inner_text(),'com nome e sem preço, avisa o que falta')
    pg.fill('#p-IA-i0-0','10'); pg.fill('#p-IA-i1-0','20')
    check(pg.locator('#hd-IA-0').inner_text().startswith('R$'),'cabeçalho mostra o total do fornecedor')
    pg.click('#k-IA-i0-0')
    check('Faltam as condições' in pg.locator('#st-IA-0').inner_text(),'depois de escolher, cobra as condições')
    pg.fill('#f-IA-0','0'); pg.fill('#z-IA-0','5'); pg.fill('#c-IA-0','À vista')
    check('Leva 1 item' in pg.locator('#st-IA-0').inner_text(),'coluna mostra quantos itens leva')
    # ---- modo foco ----
    pg.click('[data-foco="1"]')
    check(pg.locator('.map.foco').count()==1,'modo foco liga')
    check(pg.locator('.map thead th.cj-1.col-on').count()>=1 and pg.locator('.map tbody td.cj-1.col-on').count()>=1,'a coluna focada fica destacada')
    pg.keyboard.press('Escape')
    check(pg.locator('.map.foco').count()==0,'Esc sai do foco')
    pg.click('#bt-back')

    # ---- busca de fornecedor no cadastro (conector simulado) ----
    conector = """
window.claude = { use: async (n) => n !== 'mcp' ? null : ({ callTool: async (srv, tl, inp) => {
  if (inp.query.includes('count(*)')) return { payload:[{n:3568}] };
  const termo = (inp.query.match(/ilike '%([^%]*)%'/) || [])[1] || '';
  const base=[{nome:'ELÉTRICA GUARAPUAVA', razao_social:'ELETRICA GUARAPUAVA LTDA', cidade:'GUARAPUAVA', uf:'PR'},
              {nome:'ELETROCENTRO PR', razao_social:'ELETROCENTRO LTDA', cidade:'CURITIBA', uf:'PR'}];
  return { payload: base.filter(x => (x.nome+x.razao_social).toLowerCase().includes(termo)) };
}}) };
"""
    pgc = b.new_page(viewport={'width':1400,'height':900})
    pgc.on('pageerror', lambda e: erros.append('busca '+str(e)))
    pgc.add_init_script(conector)
    pgc.goto(URL); pgc.wait_for_selector('table.fila'); pgc.click('[data-open="C2609-00004"]'); pgc.wait_for_timeout(500)
    check('cadastros ativos do banco' in pgc.locator('.fonte-forn').inner_text(),'com conector, a tela diz que busca no banco')
    pgc.click('#n-MG-0'); pgc.type('#n-MG-0','ele', delay=40); pgc.wait_for_timeout(600)
    check(pgc.locator('.sug [data-sug]').count()==2,'busca traz os fornecedores do cadastro')
    check('GUARAPUAVA/PR' in pgc.locator('.sug').inner_text(),'sugestão mostra a cidade')
    pgc.keyboard.press('ArrowDown'); pgc.keyboard.press('ArrowDown'); pgc.keyboard.press('Enter'); pgc.wait_for_timeout(250)
    check(pgc.locator('#n-MG-0').input_value()=='ELETROCENTRO PR','dá para escolher pelo teclado')
    check(pgc.locator('.sug').count()==0,'a lista fecha depois de escolher')
    pgc.fill('#n-MG-1','ele'); pgc.wait_for_timeout(600)
    pgc.locator('.sug [data-sug]').first.click(); pgc.wait_for_timeout(200)
    check(pgc.locator('#n-MG-1').input_value()=='ELÉTRICA GUARAPUAVA','dá para escolher pelo clique')
    pgc.fill('#n-MG-2','zzz'); pgc.wait_for_timeout(600)
    check('Nenhum fornecedor' in pgc.locator('.sug .aviso').inner_text(),'sem resultado explica e deixa digitar')
    pgc.fill('#n-MG-2','ele'); pgc.wait_for_timeout(600); pgc.keyboard.press('Escape')
    check(pgc.locator('.sug').count()==0,'Esc fecha a lista de sugestões')
    pgc.close()
    # sem conector, cai na amostra local
    check('amostra de 120 nomes' in pg.locator('.fonte-forn').inner_text() if pg.locator('.fonte-forn').count() else True,'sem conector avisa que é amostra')

    # ---- busca pelo navegador (GitHub Pages), falando direto com o Supabase ----
    import json as _json
    pgr = b.new_page(viewport={'width':1400,'height':900})
    pgr.on('pageerror', lambda e: erros.append('rest '+str(e)))
    def _rota(route):
        u = route.request.url
        if u.endswith('/rpc/fornecedores_ativos'):
            route.fulfill(status=200, content_type='application/json', body='3568')
        elif u.endswith('/rpc/buscar_fornecedor'):
            termo = _json.loads(route.request.post_data)['termo'].lower()
            base = [{"id":"1","nome":"ELÉTRICA GUARAPUAVA","razao_social":"ELETRICA GUARAPUAVA LTDA","cidade":"GUARAPUAVA","uf":"PR"},
                    {"id":"2","nome":"ELETROCENTRO PR","razao_social":"ELETROCENTRO LTDA","cidade":"CURITIBA","uf":"PR"}]
            route.fulfill(status=200, content_type='application/json',
                          body=_json.dumps([x for x in base if termo in (x['nome']+x['razao_social']).lower()]))
        else:
            route.abort()
    pgr.route('**/rest/v1/rpc/**', _rota)
    pgr.goto(URL); pgr.wait_for_selector('table.fila'); pgr.click('[data-open="C2609-00004"]'); pgr.wait_for_timeout(600)
    check('3.568 cadastros ativos' in pgr.locator('.fonte-forn').inner_text(),'no navegador, busca no banco pela chave pública')
    pgr.click('#n-MG-0'); pgr.type('#n-MG-0','ele', delay=40); pgr.wait_for_timeout(700)
    check(pgr.locator('.sug [data-sug]').count()==2,'navegador traz os fornecedores do cadastro')
    pgr.locator('.sug [data-sug]').first.click(); pgr.wait_for_timeout(200)
    check(pgr.locator('#n-MG-0').input_value()=='ELÉTRICA GUARAPUAVA','navegador: escolher pelo clique preenche o nome')
    pgr.close()
    # ---- banco fora do ar: a tela não trava ----
    pgx = b.new_page(viewport={'width':1400,'height':900})
    pgx.on('pageerror', lambda e: erros.append('offline '+str(e)))
    pgx.route('**/rest/v1/rpc/**', lambda r: r.abort())
    pgx.goto(URL); pgx.wait_for_selector('table.fila'); pgx.click('[data-open="C2609-00004"]'); pgx.wait_for_timeout(700)
    check('sem conexão com o banco' in pgx.locator('.fonte-forn').inner_text(),'sem banco, avisa e usa a amostra local')
    check(pgx.locator('#n-MG-0').get_attribute('list')=='dl-forn','sem banco, o campo cai na lista de exemplo')
    pgx.close()

    # ---- compra mensal ----
    pg.click('[data-tab=cotar]'); pg.fill('#f-q','')
    check(pg.locator('[data-tipo="mensal"]').get_attribute('aria-disabled') is None,'Mensal virou filtro de verdade')
    pg.click('[data-tipo="mensal"]')
    check(rows()==1,'filtro mensal traz a compra do mês')
    check('Mensal' in pg.locator('tr[data-id="C2609-90004"]').inner_text(),'a fila marca a compra como mensal')
    pg.click('[data-open="C2609-90004"]'); pg.wait_for_selector('.map')
    check('Compra mensal' in pg.inner_text('.m-top'),'o mapa mostra que é compra mensal')
    check(pg.locator('.ftab').count()==3,'mensal vem separada por família')
    abas = pg.locator('#ftabs').inner_text()
    check('CC · Cozinha e copa' in abas and 'HL · Higiene e limpeza' in abas and 'ME · Escritório' in abas,'as três famílias do mês aparecem com nome')
    check(pg.locator('.map tbody tr').count()==8,'a família de alimentos lista os 8 itens')
    check(pg.locator('#bt-falta').count()==1,'compra grande ganha o atalho "só o que falta"')
    check('Só o que falta (8)' in pg.locator('#bt-falta').inner_text(),'o atalho conta quantos faltam')
    pg.fill('#n-CC-0','Atacado Exemplo'); pg.fill('#p-CC-m01-0','24,90'); pg.click('#k-CC-m01-0')
    pg.click('#bt-falta')
    check(pg.locator('.map tbody tr').count()==7,'com o atalho ligado, some o item já resolvido')
    check('mostrando 7 pendentes' in pg.locator('#map-title').inner_text(),'o título avisa que a lista está filtrada')
    pg.click('#bt-falta')
    check(pg.locator('.map tbody tr').count()==8,'dá para voltar a ver todos')
    pg.click('[data-fam=ME]')
    check(pg.locator('#bt-falta').count()==0,'família pequena não mostra o atalho')
    pg.click('#bt-back'); pg.click('[data-tipo=""]')
    pg.screenshot(path='t-mesa-fila.png', full_page=True)
    pg.click('[data-open="C2609-90001"]'); pg.screenshot(path='t-mesa-mapa.png', full_page=True)
    # mobile
    m=b.new_page(viewport={'width':400,'height':850})
    m.on('pageerror', lambda e: erros.append('mobile '+str(e)))
    m.goto(URL); m.wait_for_selector('table.fila')
    check(m.evaluate('document.documentElement.scrollWidth<=innerWidth'),'mobile fila sem scroll lateral')
    m.click('[data-open="C2609-90001"]')
    check(m.evaluate('document.documentElement.scrollWidth<=innerWidth'),'mobile mapa sem scroll lateral')
    m.screenshot(path='t-mesa-mob.png', full_page=False)
    d=b.new_page(viewport={'width':1400,'height':900}, color_scheme='dark')
    d.goto(URL); d.wait_for_selector('table.fila'); d.click('[data-tab=dev]'); d.click('[data-open="C2609-90002"]'); d.screenshot(path='t-mesa-dark.png')
    b.close()
print('\n'.join(R)); print('ERROS JS:', erros)
